# Generated by Django 4.1.4 on 2023-11-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Name')),
                ('property_type', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Type (Offplan, Developer, etc.)')),
                ('property_accommodation_type', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Accommodation Type (Appartments, Villa, Penthouse, etc.)')),
                ('property_location', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Location (name)')),
                ('property_location_description', models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Location Description')),
                ('property_units', models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Units')),
                ('property_payment_plan', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Payment Plan')),
                ('property_handover', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Handover')),
                ('property_developer', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Developer (Emaar, Sobha, etc.)')),
                ('property_bed_number', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Bed Number')),
                ('property_description', models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Description')),
                ('property_starting_price', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Starting Price (AED)')),
                ('property_priority', models.TextField(blank=True, default='', max_length=500, verbose_name='Property Priority')),
            ],
            options={
                'verbose_name': 'Hot Property',
                'verbose_name_plural': 'Hot Properties',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Name')),
                ('property_type', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Type (Offplan, Developer, etc.)')),
                ('property_accommodation_type', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Accommodation Type (Appartments, Villa, Penthouse, etc.)')),
                ('property_location', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Location (name)')),
                ('property_location_description', models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Location Description')),
                ('property_units', models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Units')),
                ('property_payment_plan', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Payment Plan')),
                ('property_handover', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Handover')),
                ('property_developer', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Developer (Emaar, Sobha, etc.)')),
                ('property_bed_number', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Bed Number')),
                ('property_description', models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Description')),
                ('property_starting_price', models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Starting Price (AED)')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='media/slider', verbose_name='Image 1')),
                ('image2', models.FileField(upload_to='media/slider', verbose_name='Image ')),
                ('image3', models.FileField(upload_to='media/slider', verbose_name='Image 3')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
