# Generated by Django 4.1.4 on 2023-11-01 10:09

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotProperty',
        ),
        migrations.CreateModel(
            name='MainPageProperty',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image1',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image2',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image3',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image4',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image5',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image6',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image7',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 7'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image8',
            field=models.FileField(default='', upload_to=website.models.get_image_path, verbose_name='Image 8'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_payment_plan',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Area (sqft)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_units',
            field=models.TextField(blank=True, default='', max_length=50000, verbose_name='Property Units Description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image2',
            field=models.FileField(upload_to='media/slider', verbose_name='Image 2'),
        ),
    ]
