# Generated by Django 4.1.4 on 2023-11-01 10:11

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_hotproperty_mainpageproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image1',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image2',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image3',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image4',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image5',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image6',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image7',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image8',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 8'),
        ),
    ]
