# Generated by Django 4.1.4 on 2023-11-03 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_property_starting_price_property_property_starting_price_aed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 6, 31, 58, 792166, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
