# Generated by Django 4.1.4 on 2023-11-03 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_property_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_highlights',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 41, 40, 124528, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_accommodation_type',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Property Type (Appartments, Villa, Penthouse, etc.)'),
        ),
    ]
