# Generated by Django 4.1.4 on 2023-11-03 13:40

import datetime
from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_property_property_highlights_alter_property_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_image9',
            field=models.FileField(blank=True, default='', upload_to=website.models.get_image_path, verbose_name='Image 9'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 40, 53, 29057, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
