# Generated by Django 4.1.4 on 2023-11-04 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_property_property_image9_alter_property_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['date'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 35, 31, 503352, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
