# Generated by Django 4.1.4 on 2023-11-04 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_property_options_property_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 40, 7, 975361, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
