# Generated by Django 4.1.4 on 2023-11-04 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_property_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('sort_order',), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 43, 11, 926662, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
