# Generated by Django 4.1.4 on 2023-11-04 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_property_options_property_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('order',), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 47, 48, 184481, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
        migrations.AlterField(
            model_name='property',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
