# Generated by Django 4.1.4 on 2023-11-19 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_property_property_type_alter_property_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(blank=True, default='', max_length=5000, verbose_name='Client Name')),
                ('client_review', models.TextField(blank=True, default='', max_length=50000, verbose_name='Client Review')),
                ('client_image', models.FileField(upload_to='media/reviews', verbose_name='Client Photo')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 12, 20, 56, 293250, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
