# Generated by Django 4.1.4 on 2023-11-19 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_bed_bed_value_alter_property_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 16, 10, 55, 911175, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
