# Generated by Django 4.1.4 on 2023-11-19 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_property_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_value',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Bedroom Value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 16, 11, 20, 137953, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
