# Generated by Django 4.1.4 on 2023-11-22 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_gallery_alter_bed_bed_value_alter_property_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(upload_to='media/profile', verbose_name='Profile Image')),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images',
            },
        ),
        migrations.DeleteModel(
            name='MainPageProperty',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image1',
            field=models.FileField(upload_to='media/gallery', verbose_name='Image 1 (max size 150x150)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.FileField(upload_to='media/gallery', verbose_name='Image 2 (max size 150x150)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.FileField(upload_to='media/gallery', verbose_name='Image 3 (max size 150x150)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image4',
            field=models.FileField(upload_to='media/gallery', verbose_name='Image 4 (max size 150x150)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image5',
            field=models.FileField(upload_to='media/gallery', verbose_name='Image 5 (max size 150x150)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image6',
            field=models.FileField(upload_to='media/gallery', verbose_name='Image 6 (max size 150x150)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 14, 46, 32, 347669, tzinfo=datetime.timezone.utc), verbose_name='Time added'),
        ),
    ]
